### ISSUE TITLE
error about missmach meshes

### ISSUE THREAD

**Issue by EduardVinter** [jvencels/EOF-Library#6]
EOF aborts calculation with error message about mismatch elements number of two meshes.

```
ERROR:: OpenFOAM2ElmerSolver: Elmer #0 has 4641 elements, OpenFOAM found 4612
OpenFOAM2Elmer Init = 0.2459315 s
```

But in Salome I have the same mesh in the melt region with equal number of elements for Elmer and OFoam.

Moreover, test cases work without any errors.

**Comment by jvencels** [comment]
Please send me the case.

**Comment by EduardVinter** [comment]
пт, 3 апр. 2020 г. в 21:03, Juris Vencels <notifications@github.com>:

**Comment by MartinKlevs** [comment]
Hello. How was this problem solved? I have the same issue.

**Comment by jvencels** [comment]
Hi Martins,

EOF-Library cannot extrapolate data outside the computation domain. Most 
often this error happens when curved surfaces are meshed with different 
algorithms or mesh sizes.

If this is the case, try
1) choosing nodal interpolation algorithm (applicable only to 
OpenFOAM2Elmer direction)
2) Modify mesh, its refinement etc.

In very rare cases we make domains (those that are coupled between Elmer 
and penFOAM) of different size by purpose and just disable (comment out) 
that error message.

Juris

**Comment by MartinKlevs** [comment]
What do i need to comment out to surpress this error? How does this ignored error affect the simulation?

**Comment by jvencels** [comment]
This is safety feature and it has to be there to inform about mesh 
mismatch. If user removes or comments these lines of code (that cause 
this error) then it is up to the user to decide whether it affects 
simulation or not.
